import {passwordRequest,type PasswordPort,type Operation} from '../supabase/functions/_shared/password-command.ts';
function assert(v:unknown,m='assertion failed'){if(!v)throw new Error(m)}
const id='22222222-2222-4222-8222-222222222222';
function fixture(){const events:string[]=[];let proven=false;const account={canonical_key:'fixture',login_username:'fixture',preferred_login:'تجربة',display_name:'تجربة',role_code:'employee',internal_email:'fixture@invalid.local',migrated_user_id:id};const op:Operation={operation_id:id,target_user_id:id,canonical_key:'fixture',login_username:'fixture',generation:1,status:'pending',write_allowed:true};const port:PasswordPort={caller:async()=>({id,session_id:id,email:account.internal_email}),accountByUser:async()=>account,accountByKey:async()=>account,begin:async()=>{events.push('begin');return op},markerMatches:async()=>proven,currentOperation:async()=>proven,samePassword:async()=>false,replace:async()=>{events.push('replace');proven=true},finish:async()=>{events.push('finish')},uncertain:async()=>{events.push('uncertain')},failed:async()=>{events.push('failed')},signIn:async()=>({access_token:'synthetic',refresh_token:'synthetic'})};return{port,events,op,setProven:(v:boolean)=>proven=v}}
function req(extra={},origin='https://ceo-msajed.pages.dev'){return new Request('https://fixture.invalid',{method:'POST',headers:{'content-type':'application/json',origin},body:JSON.stringify({access_token:'synthetic',operation_id:id,new_password:'Valid8#Fixture',...extra})})}
Deno.test('same current password does not start credential operation',async()=>{const f=fixture();f.port.samePassword=async()=>true;const r=await passwordRequest(req(),f.port,'change');assert(r.status===400);assert(!f.events.includes('begin'),'invalid same-password attempt must not change session cutoff or forced flags')});
Deno.test('successful own change proves provider write before finalizing',async()=>{const f=fixture();const r=await passwordRequest(req(),f.port,'change');assert(r.status===200);assert(f.events.join(',')==='begin,replace,finish')});
Deno.test('provider timeout keeps unresolved operation fail closed',async()=>{const f=fixture();f.port.replace=async()=>{throw Error('fixture timeout')};const r=await passwordRequest(req(),f.port,'change');assert(r.status===503);assert(f.events.join(',')==='begin,uncertain')});
Deno.test('duplicate unresolved request cannot repeat Auth write',async()=>{const f=fixture();f.op.write_allowed=false;const r=await passwordRequest(req(),f.port,'change');assert(r.status===409);assert(!f.events.includes('replace'));assert(!f.events.includes('finish'))});
Deno.test('unknown client authority fields rejected before access',async()=>{const f=fixture();const r=await passwordRequest(req({role:'ceo_office_manager'}),f.port,'reset');assert(r.status===400);assert(f.events.length===0)});
Deno.test('unauthorized origin rejected without lookup or writes',async()=>{const f=fixture();assert((await passwordRequest(req({},'https://hostile.invalid'),f.port,'change')).status===403);assert(f.events.length===0)});
Deno.test('weak and Unicode-short passwords rejected server-side',async()=>{for(const pw of ['weak','Abcdefg#','ABCDEFG8#','abcdefg8#','Abcdefg89','Aa1#xx😀']){const f=fixture();assert((await passwordRequest(req({new_password:pw}),f.port,'change')).status===400);assert(f.events.length===0)}});
Deno.test('definite provider rejection is failed, not an uncertain write',async()=>{const f=fixture();f.port.replace=async()=>{throw new Error('provider_422')};const r=await passwordRequest(req(),f.port,'change');assert(r.status===400);assert(f.events.join(',')==='begin,failed')});
Deno.test('reset replay with a different candidate cannot report assignment success',async()=>{const f=fixture();f.op.status='completed';f.op.write_allowed=false;f.setProven(true);f.port.samePassword=async()=>false;const r=await passwordRequest(req({target_key:'fixture',new_password:'Changed9#Candidate'}),f.port,'reset');assert(r.status===409,'a candidate not assigned by the completed operation must not be reported as assigned');assert(!f.events.includes('replace'))});
Deno.test('reset recovery verifies the original candidate without a second Auth write',async()=>{const f=fixture();f.op.status='uncertain';f.op.write_allowed=false;f.setProven(true);f.port.samePassword=async()=>true;const r=await passwordRequest(req({target_key:'fixture'}),f.port,'reset');assert(r.status===200);assert(f.events.join(',')==='begin,finish')});
Deno.test('completed operation superseded by a new marker cannot assert old success',async()=>{const f=fixture();f.op.status='completed';f.op.write_allowed=false;f.setProven(false);assert((await passwordRequest(req({target_key:'fixture'}),f.port,'reset')).status===409)});
