import fs from 'node:fs';import assert from 'node:assert/strict';
import {createTransactionFeedbackFixture} from './qa_isolation_fixture.mjs';
import {graphHarness} from './helpers/qa_delete_graph_harness.mjs';
const out=process.env.QA_DELETE_EVIDENCE;
const {db,scalar,id,actors,dir}=await createTransactionFeedbackFixture({modulePath:process.env.QA_DELETE_ADAPTER});
const {reset,bind,snapshot,abi,context,graph,denied,absent,unchangedExcept}=graphHarness(db,scalar,id,actors);
const tables=['transactions','transaction_assignments','transaction_assignment_users','transaction_assignment_targets','transaction_actions','transaction_action_versions','transaction_action_notes','transaction_links','transaction_routes','transaction_requests','transaction_history','transaction_participants','transaction_periods','notifications'];
const results=[],receipts={};let serial=10000;const fresh=opts=>graph(serial+=30,opts);
const test=async(name,fn)=>{try{await fn();results.push({name,status:'Passed'})}catch(e){results.push({name,status:'Failed',code:e.code,reason:e.message,where:e.where});process.exitCode=1;try{await db.exec('rollback;reset role')}catch{}}};
const deleteRoot=async(g)=>{await bind(g.owner);await db.query('delete from public.transactions where id=$1',[g.root])};
const removed=c=>c.filter(x=>x.old_references.disposition==='delete').map(x=>({table:receipts.relations[x.table_oid],row:x.old_references.source_row}));
try{
 for(const n of ['10000_qa_isolation_prerequisites','18000_qa_rest_provenance','18500_qa_core_rest_admission','19000_qa_typed_producer_references'])await db.exec(fs.readFileSync(dir+'/202610080'+n+'.sql','utf8'));
 await db.exec('grant all on all tables in schema public to service_role;grant usage,select on all sequences in schema public to service_role');
 await db.exec('update public.account_migration_users a set preferred_login=p.login_name from public.profiles p where p.id=a.migrated_user_id');
 receipts.abiBefore=await abi();const control=await graph(9800);receipts.revisionOracle={};
 // Independent native predecessor oracle BEFORE any QA guard attachments.
 for(const kind of ['assignment','action']){await db.exec('begin');const before=await scalar('select activity_revision::int from public.transactions where id=$1',[control.root]);await db.query(`delete from public.transaction_${kind==='action'?'actions':'assignments'} where id=$1`,[control[kind]]);receipts.revisionOracle[kind]=await scalar('select activity_revision::int from public.transactions where id=$1',[control.root])-before;await db.exec('rollback')}
 const installBefore=await snapshot();const securitySQL="select jsonb_build_object('tables',(select jsonb_agg(jsonb_build_object('oid',oid,'owner',relowner,'acl',relacl,'rls',relrowsecurity,'force_rls',relforcerowsecurity) order by oid) from pg_class where relkind='r' and relnamespace in ('public'::regnamespace,'app_private'::regnamespace,'auth'::regnamespace)),'policies',(select jsonb_agg(to_jsonb(x) order by oid) from pg_policy x))";receipts.securityBefore=await scalar(securitySQL);await db.exec(fs.readFileSync(dir+'/20261008019500_qa_delete_completion.sql','utf8'));receipts.securityAfter=await scalar(securitySQL);receipts.abiAfterInstall=await abi();
 await test('G5 install preserves all data and revision functions OIDs byte-for-byte ABI',async()=>{assert.deepEqual(await snapshot(),installBefore);for(const f of receipts.abiBefore.filter(x=>['transaction_revision_before','transaction_child_revision_after'].includes(x.proname)))assert.deepEqual(receipts.abiAfterInstall.find(x=>x.oid===f.oid),f)});
 await test('G5 all other function ABIs and all table ACL/RLS/policies unchanged',async()=>{const replaced=new Set(['qa_capture_graph','qa_delete_capture','qa_reference_guard_before_row','qa_sql_old_key_valid']);for(const f of receipts.abiBefore.filter(x=>!replaced.has(x.proname)))assert.deepEqual(receipts.abiAfterInstall.find(x=>x.oid===f.oid),f);for(const f of receipts.abiBefore.filter(x=>replaced.has(x.proname))){const a=structuredClone(receipts.abiAfterInstall.find(x=>x.oid===f.oid)),b=structuredClone(f);delete a.def;delete b.def;assert.deepEqual(a,b)}assert.deepEqual(receipts.securityAfter,receipts.securityBefore)});
 const qaRun=id(9600);await db.query("insert into app_private.qa_runs values($1,'active',true,clock_timestamp()+interval '1 hour',clock_timestamp())",[qaRun]);await db.query("insert into app_private.qa_account_manifest values($1,'fixture_manager','fixture_manager','current_owned_QA',$2,$3,$4,null)",[actors.manager,qaRun,id(9601),id(9602)]);await db.query("insert into app_private.qa_run_members values($1,$2,'manager',true)",[qaRun,actors.manager]);await db.query('update public.transaction_assignment_targets set user_id=$1 where id=$2',[actors.manager,id(9805)]);
 for(const t of tables)await db.exec(`create trigger graph_reference before insert or update or delete on public.${t} for each row execute function app_private.qa_reference_guard_before_row()`);
 for(const t of ['transactions','transaction_assignments','transaction_actions'])await db.exec(`create trigger graph_capture before delete on public.${t} for each row execute function app_private.qa_delete_capture()`);
 await db.exec("create function public.graph_test_consume(p jsonb) returns void language sql security definer set search_path='' as $$select app_private.qa_delete_consume_context(jsonb_populate_record(null::app_private.qa_sql_operation_context,p))$$;revoke all on function public.graph_test_consume(jsonb) from public;grant execute on function public.graph_test_consume(jsonb) to service_role");
 receipts.target=db.connection;receipts.relations=Object.fromEntries((await db.query("select oid,(case when relnamespace='public'::regnamespace then 'public.' else 'app_private.' end)||relname name from pg_class where oid=any(app_private.qa_delete_graph_relations())")).rows.map(x=>[x.oid,x.name]));
 await test('G1 ordinary 15-relation single DELETE commits only after exact dependencies absent',async()=>{const g=await fresh(),before=await snapshot();await db.exec('begin');await deleteRoot(g);const c=await context();assert.equal(c.length,15);assert.equal(new Set(c.map(x=>x.table_oid)).size,15);for(const x of c){assert.equal(x.old_references.seen,false);if(['public.transactions','public.transaction_assignments','public.transaction_actions'].includes(receipts.relations[x.table_oid])){assert.equal(x.old_references.registered,true);assert.deepEqual(x.old_references.registered_old,x.old_references.row)}assert.equal(await scalar(`select count(*)::int from ${receipts.relations[x.table_oid]} t where to_jsonb(t) @> $1::jsonb`,[x.old_key]),0)}receipts.timing={beforeCommitContext:c,allExactRowsAbsent:true};await bind();await db.exec('commit');await absent(g);await unchangedExcept(before,removed(c));receipts.timing.afterCommitContext=await context()});
 await test('G2 assignment FK52 SET NULL exact action and descendants survive; native revision oracle',async()=>{const g=await fresh(),before=await snapshot(),rev=await scalar('select activity_revision::int from public.transactions where id=$1',[g.root]);await db.exec('begin');await bind();await db.query('delete from public.transaction_assignments where id=$1',[g.assignment]);const c=await context(),survivor=c.find(x=>receipts.relations[x.table_oid]==='public.transaction_actions');assert.equal(survivor.old_references.disposition,'setnull');assert.equal(survivor.old_references.registered,false);assert.equal(c.some(x=>['public.transaction_action_notes','public.transaction_action_versions'].includes(receipts.relations[x.table_oid])),false);assert.deepEqual((await db.query('select to_jsonb(x) row from public.transaction_actions x where id=$1',[g.action])).rows[0].row,{...survivor.old_references.source_row,assignment_id:null});await bind();await db.exec('commit');await reset();assert.equal((await context()).length,0);assert.equal(await scalar('select activity_revision::int from public.transactions where id=$1',[g.root])-rev,receipts.revisionOracle.assignment);const after=await snapshot();for(const t of Object.keys(before)){const expected=before[t].filter(x=>!removed(c).some(r=>r.table===t&&JSON.stringify(r.row)===JSON.stringify(x.row)));if(t==='public.transaction_actions')for(const x of expected)if(x.row.id===g.action)x.row.assignment_id=null;if(t==='public.transactions')for(const arr of [expected,after[t]])for(const x of arr)if(x.row.id===g.root)for(const k of ['activity_revision','last_activity_at','updated_at'])delete x.row[k];assert.deepEqual(after[t],expected,t)}});
 await test('G2 native multi-path adapter accepts exact transient OLD binding at deferred completion',async()=>{const g=await fresh(),before=await snapshot();await db.exec('begin');await deleteRoot(g);const c=await context(),action=c.find(x=>receipts.relations[x.table_oid]==='public.transaction_actions');assert.equal(action.old_references.source_row.assignment_id,g.assignment);await reset();await db.query("update app_private.qa_sql_operation_context set old_references=jsonb_set(jsonb_set(old_references,'{row,assignment_id}','null'),'{registered_old,assignment_id}','null') where backend_pid=pg_backend_pid() and sql_xid=pg_current_xact_id() and operation_id=$1 and table_oid='public.transaction_actions'::regclass",[action.operation_id]);const adapted=(await context()).find(x=>receipts.relations[x.table_oid]==='public.transaction_actions');assert.deepEqual(adapted.old_references.registered_old,{...action.old_references.source_row,assignment_id:null});receipts.transientSetNull={evidenceClass:'Native deferred consumer state permutation; native FK52 UPDATE producer independently exercised by assignment survivor case. Alternate root FK callback order was NOT observed, and is not claimed.',source:adapted.old_references.source_row,adaptedDeleteOLD:adapted.old_references.registered_old};await bind();await db.exec('commit');await absent(g);await unchangedExcept(before,removed(c))});
 await test('G1 owned QA populated root preserves accepted successful deletion',async()=>{await reset();await db.query('insert into app_private.qa_transaction_manifest values($1,$2,$3,null)',[id(serial+30),qaRun,id(9700)]);const g=await fresh({owner:actors.manager}),before=await snapshot();await db.exec('begin');await deleteRoot(g);const c=await context();await bind(actors.manager);await db.exec('commit');await absent(g);await unchangedExcept(before,removed(c))});
 await test('G1 foreign indirect target reference rejects atomically before deletion',async()=>{await denied('delete from public.transactions where id=$1',[control.root],'42501')});
 await test('G3 reference-before-capture ordering preserves exact successful graph deletion',async()=>{const g=await fresh(),before=await snapshot();await db.exec('begin');await reset();for(const t of ['transactions','transaction_assignments','transaction_actions'])await db.exec(`alter trigger graph_capture on public.${t} rename to zz_graph_capture`);await deleteRoot(g);const c=await context();await bind();await db.exec('commit');await absent(g);await unchangedExcept(before,removed(c));await reset();for(const t of ['transactions','transaction_assignments','transaction_actions'])await db.exec(`alter trigger zz_graph_capture on public.${t} rename to graph_capture`)});
 await test('G2 transient adapter rejects any non-FK-field changes atomically',async()=>{const g=await fresh(),before=await snapshot();await db.exec('begin');await deleteRoot(g);await reset();await db.query("update app_private.qa_sql_operation_context set old_references=jsonb_set(old_references,'{row,action_text}','\"tampered\"') where table_oid='public.transaction_actions'::regclass");await bind();let code;try{await db.exec('commit')}catch(e){code=e.code}assert.equal(code,'42501');await db.exec('rollback');assert.deepEqual(await snapshot(),before)});
 await test('G3 standalone action exact owner matches native live-parent revision arithmetic',async()=>{const g=await fresh(),before=await snapshot(),rev=await scalar('select activity_revision::int from public.transactions where id=$1',[g.root]);await db.exec('begin');await bind();await db.query('delete from public.transaction_actions where id=$1',[g.action]);const c=await context();assert.equal(c.length,3);await bind();await db.exec('commit');await reset();assert.equal(await scalar('select activity_revision::int from public.transactions where id=$1',[g.root])-rev,receipts.revisionOracle.action);await unchangedExcept(before,removed(c),[g.root]);assert.equal((await context()).length,0)});
 await test('G3 disjoint multi-root DELETE has two independent exact owners',async()=>{const a=await fresh(),b=await fresh(),before=await snapshot();await db.exec('begin');await bind();await db.query('delete from public.transactions where id=any($1::uuid[])',[[a.root,b.root]]);const c=await context();assert.equal(new Set(c.map(x=>x.operation_id)).size,2);await bind();await db.exec('commit');await absent(a);await absent(b);await unchangedExcept(before,removed(c))});
 await test('G3 duplicate ownership of SET NULL survivor rejected atomically',async()=>{const g=await fresh();await db.exec('begin');await bind();await db.query('delete from public.transaction_assignments where id=$1',[g.assignment]);const pending=await context();await db.exec('savepoint overlap');await bind();let got;try{await db.query('delete from public.transaction_actions where id=$1',[g.action])}catch(e){got=e.code}assert.equal(got,'42501');await db.exec('rollback to overlap');assert.deepEqual(await context(),pending);await bind();await db.exec('commit');await reset();assert.equal(await scalar('select count(*)::int from public.transaction_actions where id=$1 and assignment_id is null',[g.action]),1);assert.equal((await context()).length,0)});
 await test('G1 owner-first owner-last private event state permutations independent of queue order',async()=>{for(const last of [false,true]){const g=await fresh();await db.exec('begin');await deleteRoot(g);const c=await context();const ordered=c.sort((x,y)=>{const ox=x.table_oid===Number(x.old_references.capture_owner_oid),oy=y.table_oid===Number(y.old_references.capture_owner_oid);return (Number(ox)-Number(oy))*(last?1:-1)});for(let i=0;i<ordered.length;i++){const ev=structuredClone(ordered[i]);ev.old_references={row:ev.old_references.source_row,source_row:ev.old_references.source_row,refs:ev.old_references.refs,disposition:ev.old_references.disposition,registered:false,seen:false};await bind();await db.query('select public.graph_test_consume($1::jsonb)',[ev]);const now=await context();if(i<ordered.length-1){assert.equal(now.length,c.length);assert.equal(now.filter(x=>x.old_references.seen).length,i+1)}else assert.equal(now.length,0)}await db.exec('rollback')}receipts.orderingProof='Real PG consumer event permutations rolled back; actual native queue commits exercised separately; no queue order assumed.'});
 await test('G1 duplicate callback rejected not inferred from missing or seen context',async()=>{const g=await fresh();await db.exec('begin');await deleteRoot(g);const ev=(await context())[0];await bind();await db.query('select public.graph_test_consume($1::jsonb)',[ev]);await db.exec('savepoint duplicate');let code;try{await db.query('select public.graph_test_consume($1::jsonb)',[ev])}catch(e){code=e.code}assert.equal(code,'42501');await db.exec('rollback');assert.equal((await context()).length,0)});
 await test('G1 missing actual BEFORE registration prevents success and restores full state',async()=>{const g=await fresh(),before=await snapshot();await db.exec('begin');await deleteRoot(g);await reset();await db.query("update app_private.qa_sql_operation_context set old_references=jsonb_set(old_references,'{registered}','false') where table_oid='public.transaction_actions'::regclass");await bind();let code;try{await db.exec('commit')}catch(e){code=e.code}assert.equal(code,'55000');await db.exec('rollback');assert.deepEqual(await snapshot(),before)});
 const catalogCases=[
 ['missing capture',"drop trigger graph_capture on public.transactions"],
 ['duplicate capture',"create trigger extra_capture before delete on public.transactions for each row execute function app_private.qa_delete_capture()"],
 ['conditional capture',"drop trigger graph_capture on public.transactions;create trigger graph_capture before delete on public.transactions for each row when(false) execute function app_private.qa_delete_capture()"],
 ['BEFORE suppressor',"create function public.graph_suppress() returns trigger language plpgsql as $$begin return null;end$$;create trigger zz_graph_suppress before delete on public.transactions for each row execute function public.graph_suppress()"],
 ['disabled trigger',"alter table public.transactions disable trigger graph_capture"],
 ['replica trigger',"alter table public.transactions enable replica trigger graph_capture"],
 ['replication role',"set local session_replication_role=replica"],
 ['rule',"create rule graph_rule as on delete to public.transactions do instead nothing"],
 ['declarative partition attachment',"create table public.graph_partitions (like public.transactions including defaults including constraints) partition by range(id);alter table public.graph_partitions attach partition public.transactions for values from (minvalue) to (maxvalue)"],
 ['partition inheritance',"create table public.graph_inherited() inherits(public.transactions)"],
 ['late deferred writer',"create function public.graph_writer() returns trigger language plpgsql as $$begin update public.transactions set title='late' where id=new.id;return null;end$$;create constraint trigger zz_graph_late after insert on public.transactions deferrable initially deferred for each row execute function public.graph_writer()"],
 ['reentrant forced callback',"create function public.graph_force() returns trigger language plpgsql as $$begin set constraints all immediate;return old;end$$;create trigger zz_graph_force before delete on public.transactions for each row execute function public.graph_force()"],
 ['private completion suppressed',"alter table app_private.qa_sql_operation_context disable trigger qa_delete_context_completion"],
 ['revision body drift',"create or replace function app_private.transaction_revision_before() returns trigger language plpgsql security definer set search_path='' as $$begin return new;end$$"],
 ['FK policy drift',"alter table public.transaction_actions drop constraint transaction_actions_assignment_id_fkey;alter table public.transaction_actions add constraint transaction_actions_assignment_id_fkey foreign key(assignment_id) references public.transaction_assignments(id) on delete cascade"]
 ];for(const[name,ddl]of catalogCases)await test('G3/G4 catalog rejects '+name,async()=>{const g=await fresh({full:false});if(['replication role','rule'].includes(name)){const before=await snapshot();await db.exec('begin');await db.exec(ddl);let code;try{await db.exec('select app_private.qa_delete_catalog_closed()')}catch(e){code=e.code}assert.equal(code,'55000');await db.exec('rollback');assert.deepEqual(await snapshot(),before);receipts[name+'Scope']='Trusted-admin unsupported-catalog attestation rejection, not a suppressed-trigger business DELETE claim';}else await denied('delete from public.transactions where id=$1',[g.root],'55000',()=>db.exec(ddl))});
 await test('G3 application roles cannot enter replication or rewrite-rule DDL bypass paths',async()=>{await denied('set session_replication_role=replica',[],'42501');await denied('create rule application_rule as on delete to public.transactions do instead nothing',[],'42501');await reset();for(const role of ['anon','authenticated','service_role']){assert.equal(await scalar("select has_schema_privilege($1,'public','CREATE')",[role]),false);assert.equal(await scalar("select rolsuper from pg_roles where rolname=$1",[role]),false)}});
 await test('G4 forced IMMEDIATE before DELETE is atomic premature 55000',async()=>{const g=await fresh(),before=await snapshot();await db.exec('begin;set constraints all immediate');await bind();let code;try{await db.query('delete from public.transactions where id=$1',[g.root])}catch(e){code=e.code}assert.equal(code,'55000');await db.exec('rollback');assert.deepEqual(await snapshot(),before)});
 await test('G4 forced after DELETE then DEFERRED fresh operation guarded normally',async()=>{const g=await fresh(),next=await fresh();await db.exec('begin');await deleteRoot(g);await db.exec('set constraints all immediate');assert.equal((await context()).length,0);await db.exec('set constraints all deferred');await deleteRoot(next);await bind();await db.exec('commit');await absent(g);await absent(next)});
 await test('G4 pending captured-key recreation denies without consuming context',async()=>{const g=await fresh({full:false});await db.exec('begin');await deleteRoot(g);const pending=await context();await db.exec('savepoint recreated');await bind();let code;try{await db.query("insert into public.transactions(id,number,title,created_by) values($1,'RECREATED','synthetic',$2)",[g.root,actors.employee])}catch(e){code=e.code}assert.equal(code,'42501');await db.exec('rollback to recreated');assert.deepEqual(await context(),pending);await bind();await db.exec('commit');await absent(g)});
 await test('G4 operation-local reclaimed key fresh guarded recreation succeeds',async()=>{const g=await fresh({full:false});await db.exec('begin');await deleteRoot(g);await db.exec('set constraints all immediate;set constraints all deferred');await bind();await db.query("insert into public.transactions(id,number,title,created_by) values($1,'FRESH-RECREATE','synthetic',$2)",[g.root,actors.employee]);await db.exec('commit');await reset();assert.equal(await scalar('select count(*)::int from public.transactions where id=$1',[g.root]),1);assert.equal((await context()).length,0)});
 await test('G4 later catalog mutation rejects COMMIT and restores exact full snapshot',async()=>{const g=await fresh(),before=await snapshot();await db.exec('begin');await deleteRoot(g);await reset();await db.exec('create rule late_graph_rule as on delete to public.transaction_assignments do instead nothing');await bind();let code;try{await db.exec('commit')}catch(e){code=e.code}assert.equal(code,'55000');await db.exec('rollback');assert.deepEqual(await snapshot(),before)});
 await test('G1 callback actor drift denies without partial committed cleanup',async()=>{const g=await fresh(),before=await snapshot();await db.exec('begin');await deleteRoot(g);await bind(actors.manager);let code;try{await db.exec('commit')}catch(e){code=e.code}assert.equal(code,'42501');await db.exec('rollback');assert.deepEqual(await snapshot(),before)});
 for(const kind of ['abort','release','completed'])await test('G5 savepoint '+kind+' pairs events registrations seen and reclaim',async()=>{const outer=await fresh(),inner=await fresh();await db.exec('begin');await deleteRoot(outer);if(kind==='completed')await db.exec('set constraints all immediate;set constraints all deferred');const pending=await context();await db.exec('savepoint sp_inner');await deleteRoot(inner);if(kind==='completed')await db.exec('set constraints all immediate');if(kind==='release')await db.exec('release sp_inner');else{await db.exec('rollback to sp_inner');assert.deepEqual(await context(),pending)}await bind();await db.exec('commit');await absent(outer);await reset();assert.equal(await scalar('select count(*)::int from public.transactions where id=$1',[inner.root]),kind==='release'?0:1);assert.equal((await context()).length,0)});
 await test('G5 no-op child update and distinct live parent reparenting arithmetic preserved',async()=>{const g=await fresh(),other=await fresh({full:false});await bind();const rev=await scalar('select activity_revision::int from public.transactions where id=$1',[g.root]);await db.query('update public.transaction_action_versions set body=body where id=$1',[g.version]);assert.equal(await scalar('select activity_revision::int from public.transactions where id=$1',[g.root]),rev);const otherRev=await scalar('select activity_revision::int from public.transactions where id=$1',[other.root]);await db.query('update public.transaction_actions set transaction_id=$1,assignment_id=null where id=$2',[other.root,g.action]);assert.equal(await scalar('select activity_revision::int from public.transactions where id=$1',[g.root]),rev+1);assert.equal(await scalar('select activity_revision::int from public.transactions where id=$1',[other.root]),otherRev+1);await reset();assert.equal((await context()).length,0)});
 await test('G1 all callers lack private context and consumer authority',async()=>{await reset();for(const role of ['anon','authenticated','service_role']){assert.equal(await scalar("select has_table_privilege($1,'app_private.qa_sql_operation_context','SELECT,INSERT,UPDATE,DELETE')",[role]),false);assert.equal(await scalar("select has_function_privilege($1,'app_private.qa_delete_consume_context(app_private.qa_sql_operation_context)','EXECUTE')",[role]),false)}});
 receipts.finalABI=await abi();await test('G5 final original revisions byte-exact OID ABI security config preserved',async()=>{for(const f of receipts.abiBefore.filter(x=>['transaction_revision_before','transaction_child_revision_after'].includes(x.proname)))assert.deepEqual(receipts.finalABI.find(x=>x.oid===f.oid),f);assert.equal((await context()).length,0)});receipts.finalSnapshot=await snapshot();receipts.catalog=(await db.query('select app_private.qa_delete_catalog_snapshot() catalog')).rows[0].catalog;
}catch(e){try{await db.exec('rollback;reset role')}catch{};results.push({name:'setup or unhandled',status:'Failed',code:e.code,reason:e.message,where:e.where});process.exitCode=1}
finally{fs.writeFileSync(out+'/MATRIX_'+process.env.QA_GRAPH_MODE+'.json',JSON.stringify({results,receipts,counts:Object.fromEntries(['Passed','Failed','Skipped','XFail'].map(s=>[s,results.filter(x=>x.status===s).length]))},null,2));console.log(JSON.stringify(results));await db.close()}
