// Real owned PostgreSQL: password reset/QA lifecycle/frame/rollback integration.
// Synthetic Auth rows are not real Auth candidates or native E2E acceptance.
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createPasswordGuardFixture} from './qa_password_fixture.mjs';
assert.ok(process.env.QA_LOCAL_PG_MODULE);const O='C:/Users/FAiSAL/AppData/Local/hermes/cache/scratch/qa-autonomous-completion/sql-core-password';const report={local_postgresql:true,synthetic_auth:true,provider_actions:0,remote_actions:0,checks:[]};
const f=await createPasswordGuardFixture({modulePath:process.env.QA_LOCAL_PG_MODULE,beforeGuards:async f=>{
 const {db,id,actors}=f;await db.query('delete from public.user_roles where user_id=$1',[actors.ceo]);await db.query("insert into public.user_roles(user_id,role_code,is_primary) values($1,'ceo_office_manager',true)",[actors.ceo]);await db.query("update public.account_migration_users set role_code='ceo_office_manager' where migrated_user_id=$1",[actors.ceo]);
 for(const [user,run] of [[actors.secretary,id(99501)],[actors.otherSecretary,id(99502)],[actors.stranger,id(99503)]]){
  const a=(await db.query('select * from public.account_migration_users where migrated_user_id=$1',[user])).rows[0];await db.query("insert into app_private.qa_runs(run_id,phase,active,expires_at) values($1,'active',true,clock_timestamp()+interval '1 hour')",[run]);await db.query("insert into app_private.qa_account_manifest(user_id,canonical_key,login_alias,principal_class,run_id,owned_creation_operation,owned_creation_receipt_id) values($1,$2,$3,'current_owned_QA',$4,$5,$6)",[user,a.canonical_key,a.login_username,run,id(99600+Number(user.slice(-12))),id(99700+Number(user.slice(-12)))]);await db.query('insert into app_private.qa_run_members values($1,$2,$3,true)',[run,user,a.role_code]);
 }
}});const {db,scalar,id,actors}=f;report.engine=db.connection;
const check=n=>report.checks.push({name:n,pass:true});
const snap=async()=>{await db.exec('reset role');const o={};for(const t of (await db.query("select schemaname,tablename from pg_tables where schemaname in ('auth','public','app_private') order by 1,2")).rows)o[t.schemaname+'.'+t.tablename]=(await db.query(`select to_jsonb(t) row from "${t.schemaname}"."${t.tablename}" t order by to_jsonb(t)::text`)).rows;for(const s of (await db.query("select n.nspname,c.relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where c.relkind='S' and n.nspname in ('auth','public','app_private')")).rows)o['sequence:'+s.nspname+'.'+s.relname]=(await db.query(`select last_value::text,is_called from "${s.nspname}"."${s.relname}"`)).rows;return o;};
const headers=async(u,s,h,extra={})=>{await db.exec('reset role');await db.query("select set_config('request.jwt.claims',$1,false),set_config('request.headers',$2,false)",[JSON.stringify({role:'service_role'}),JSON.stringify({'x-qa-actor-user':u,'x-qa-actor-sid':s,'x-qa-candidate-handle':h,...extra})]);await db.exec('set role service_role');};
const deny=async(n,fn,code='42501')=>{const b=await snap();let e;try{await fn();}catch(x){e=x;}assert.ok(e,n+' unexpectedly allowed');assert.equal(e.code,code,n+': '+e.message);assert.deepEqual(await snap(),b,n+' altered protected tables or sequences');check(n);};
const start=async(u,s,key,kind,op,h)=>{await headers(u,s,h);return scalar('select public.account_password_begin_internal($1,$2,$3,$4,$5)',[u,s,key,kind,op]);};
const dispatch=async(op,h,g=1)=>(await db.query('select * from public.qa_password_dispatch_internal($1,$2,$3)',[op,g,h])).rows[0];
const proof=async(op,h,u,email,verified,g=1)=>{await db.exec('reset role');await db.query("update auth.users set raw_app_meta_data=jsonb_build_object('msajed_password_operation',$2::text,'msajed_password_generation',$3::text) where id=$1",[u,op,g]);await db.query('insert into auth.sessions(id,user_id,created_at) values($1,$2,clock_timestamp())',[verified,u]);return {operation_id:op,generation:g,candidate_handle:h,target_user_id:u,target_email:email,project_ref:'movzojtnkkmdsjhmlgtq',session_id:verified,issuer:'https://movzojtnkkmdsjhmlgtq.supabase.co/auth/v1',claim_role:'authenticated',observed_at:await scalar('select clock_timestamp()::text')};};
const preserveExcept=async(before,users,operations)=>{const after=await snap();for(const [table,rows] of Object.entries(before)){
 if(table==='public.profiles'){assert.deepEqual(after[table].filter(x=>!users.includes(x.row.id)),rows.filter(x=>!users.includes(x.row.id)));continue;}
 if(table==='public.account_migration_users'){assert.deepEqual(after[table].filter(x=>!users.includes(x.row.migrated_user_id)),rows.filter(x=>!users.includes(x.row.migrated_user_id)));continue;}
 if(table==='app_private.account_credential_state'){assert.deepEqual(after[table].filter(x=>!users.includes(x.row.user_id)),rows.filter(x=>!users.includes(x.row.user_id)));continue;}
 if(table==='app_private.account_password_operations'){assert.deepEqual(after[table].filter(x=>!operations.includes(x.row.operation_id)),rows.filter(x=>!operations.includes(x.row.operation_id)));continue;}
 if(table==='public.audit_log'){assert.deepEqual(after[table].filter(x=>!operations.includes(x.row.meta.operation_id)),rows.filter(x=>!operations.includes(x.row.meta.operation_id)));continue;}
 if(table==='sequence:public.audit_log_id_seq')continue;
 assert.deepEqual(after[table],rows,'unrelated full state: '+table);
 }};
try{
 for(const role of ['anon','authenticated','service_role']){
  for(const perm of ['SELECT','INSERT','UPDATE','DELETE'])assert.equal(await scalar("select has_table_privilege($1,'app_private.qa_password_frames',$2)",[role,perm]),false);
  assert.equal(await scalar("select has_function_privilege($1,'app_private.qa_pw_effect(oid,jsonb,boolean)','EXECUTE')",[role]),false);
 }check('no_caller_frame_or_effect_authority');
 // The office actor must remain independent of target cutoff changes.
 const actor=actors.ceo,sid=id(1004),target=actors.employee,op=id(99801),h=id(99802);
 const base=await snap();await deny('nonoffice_reset_DENY',async()=>start(actors.manager,id(1002),'fixture_employee','reset',op,h));
 assert.equal((await start(actor,sid,'fixture_employee','reset',op,h)).write_allowed,true);await preserveExcept(base,[target],[op]);check('native_reset_begin_actor_not_target_preserves_other_full_state');
 await db.exec('reset role');const ac=await scalar('select session_valid_after::text from app_private.account_credential_state where user_id=$1',[actor]);const tc=await scalar('select session_valid_after::text from app_private.account_credential_state where user_id=$1',[target]);assert.notEqual(ac,tc);assert.equal(await scalar("select (qa_control->>'original_session_cutoff')::timestamptz::text from app_private.account_password_operations where operation_id=$1",[op]),ac);check('separate_reset_actor_target_cutoffs');
 await db.query('update app_private.account_credential_state set session_valid_after=clock_timestamp() where user_id=$1',[actor]);await deny('reset_actor_revocation_not_target_exemption',async()=>{await headers(actor,sid,h);await dispatch(op,h);});await db.query('update app_private.account_credential_state set session_valid_after=$2::timestamptz where user_id=$1',[actor,ac]);
 await db.query("update app_private.account_credential_state set session_valid_after=session_valid_after+interval '1 microsecond' where user_id=$1",[target]);await deny('target_cutoff_one_microsecond_drift_DENY',async()=>{await headers(actor,sid,h);await dispatch(op,h);});await db.query('update app_private.account_credential_state set session_valid_after=$2::timestamptz where user_id=$1',[target,tc]);
 await headers(actor,sid,h);assert.equal((await dispatch(op,h)).dispatch_state,'admitted_new');
 await db.exec('reset role');await db.query("insert into public.user_permissions(user_id,permission_code,effect) values($1,'profiles.admin_reset_password','deny')",[actor]);await deny('reset_permission_revoked_continuation_DENY',async()=>{await headers(actor,sid,h);await scalar('select public.account_password_unknown_internal($1)',[op]);});await db.query("delete from public.user_permissions where user_id=$1 and permission_code='profiles.admin_reset_password'",[actor]);
 const p=await proof(op,h,target,'employee@fixture.invalid',id(99803));
 await db.exec('alter table public.audit_log alter column created_at set default clock_timestamp()');await deny('audit_default_drift_zero_effects_and_no_sequence_allocation',async()=>{await headers(actor,sid,h,{'x-qa-candidate-proof':JSON.stringify(p)});await scalar('select public.account_password_finish_internal($1,1)',[op]);});await db.exec('alter table public.audit_log alter column created_at set default now()');
 await db.exec('alter sequence public.audit_log_id_seq cycle');await deny('audit_identity_sequence_drift_DENY_before_allocation',async()=>{await headers(actor,sid,h,{'x-qa-candidate-proof':JSON.stringify(p)});await scalar('select public.account_password_finish_internal($1,1)',[op]);});await db.exec('alter sequence public.audit_log_id_seq no cycle');
 const beforeFinish=await snap();await headers(actor,sid,h,{'x-qa-candidate-proof':JSON.stringify(p)});assert.equal((await scalar('select public.account_password_finish_internal($1,1)',[op])).status,'completed');await preserveExcept(beforeFinish,[target],[op]);assert.equal(await scalar('select must_change_password from public.profiles where id=$1',[target]),true);assert.equal(await scalar('select session_valid_after::text from app_private.account_credential_state where user_id=$1',[actor]),ac);check('native_reset_finish_exact_own_target_effects_only');
 // Existing native FK/revision metadata is retained by final composer.
 assert.equal(await scalar("select count(*)::int from pg_proc where proname in ('transaction_revision_before','transaction_child_revision_after')"),2);check('original_revision_functions_retained');
 // Catalog suppressors cannot produce a success with missing effects.
 await db.exec("create function app_private.qa_fixture_suppress() returns trigger language plpgsql as $$begin return null;end$$;create trigger aa_fixture_suppress before update on public.profiles for each row execute function app_private.qa_fixture_suppress()");
 await deny('later_BEFORE_suppressor_rejected_transactionally',async()=>start(actors.manager,id(1002),'fixture_manager','change',id(99811),id(99812)),'55000');await db.exec('drop trigger aa_fixture_suppress on public.profiles;drop function app_private.qa_fixture_suppress()');
 // Exact durable pre-halt admissions alone reconcile. No normal business authority.
 for(const [name,run,phase,offset] of [['secretary',id(99501),'halted',20],['otherSecretary',id(99502),'expired',30]]){
  const u=actors[name],s=id(1000+Number(u.slice(-12))),operation=id(99800+offset+1),handle=id(99800+offset+2);await start(u,s,'fixture_'+name.toLowerCase(),'change',operation,handle);await headers(u,s,handle);await dispatch(operation,handle);
  await db.exec('reset role');await db.query("update app_private.qa_runs set active=false,phase=$2,expires_at=case when $2='expired' then clock_timestamp()-interval '1 second' else expires_at end where run_id=$1",[run,phase]);await db.query('update app_private.qa_run_members set active=false where run_id=$1',[run]);
  await deny(phase+'_normal_business_DENY',async()=>{await headers(u,s,handle);await db.query("insert into public.notifications(user_id,title,event_type) values($1,'deny','fixture')",[u]);});
  await headers(u,s,handle);assert.equal((await scalar('select public.account_password_unknown_internal($1)',[operation])).status,'uncertain');const pr=await proof(operation,handle,u,name+'@fixture.invalid',id(99800+offset+3));const b=await snap();await headers(u,s,handle,{'x-qa-candidate-proof':JSON.stringify(pr)});assert.equal((await scalar('select public.account_password_finish_internal($1,1)',[operation])).status,'completed');await preserveExcept(b,[u],[operation]);check(phase+'_original_candidate_reconciliation_only');
 }
 // A prepared operation cannot use lifecycle reconciliation to mint admission.
 const u=actors.stranger,s=id(1008),prepared=id(99841),handle=id(99842);await start(u,s,'fixture_stranger','change',prepared,handle);await db.exec('reset role');await db.query("update app_private.qa_runs set phase='halted',active=false where run_id=$1",[id(99503)]);
 await deny('halted_prepared_no_new_dispatch',async()=>{await headers(u,s,handle);await dispatch(prepared,handle);});await deny('halted_prepared_no_unknown_reconciliation',async()=>{await headers(u,s,handle);await scalar('select public.account_password_unknown_internal($1)',[prepared]);});
 // Savepoint failure restores journal, effects and frames in the same subtransaction.
 const b=await snap();await db.exec('begin;savepoint owned_pw');await headers(actors.assistant,id(1003),id(99852));assert.equal((await scalar('select public.account_password_begin_internal($1,$2,$3,$4,$5)',[actors.assistant,id(1003),'fixture_assistant','change',id(99851)])).write_allowed,true);await db.exec('reset role');assert.equal(await scalar('select count(*)::int from app_private.qa_password_frames'),0);await db.exec('set constraints app_private.qa_password_frame_completion immediate');check('forced_firing_after_success_observes_closed_frame');
 // Rollback a genuinely successful begin at the savepoint, not a simulated call.
 await db.exec('rollback to savepoint owned_pw;release savepoint owned_pw;commit');assert.deepEqual(await snap(),b);check('native_savepoint_release_rollback_zero_frames_and_effects');
 // One active PID/xid frame and atomic, full-row, single-use consumption.
 const preparedReset=id(99801); // completed replay still has original admitted proof.
 await db.exec(`create function public.qa_fixture_double_frame() returns void language plpgsql security definer set search_path='' as $$begin perform app_private.qa_pw_open('observe','${preparedReset}');perform app_private.qa_pw_open('observe','${preparedReset}');end $$;`);
 await deny('one_active_PID_xid_frame',async()=>{await headers(actor,sid,h);await db.exec('select public.qa_fixture_double_frame()');},'23505');await db.exec('drop function public.qa_fixture_double_frame()');
 await db.exec(`create function public.qa_fixture_double_consume() returns void language plpgsql security definer set search_path='' as $$declare r jsonb;begin perform app_private.qa_pw_open('observe','${preparedReset}');select to_jsonb(x) into r from public.profiles x where id='${target}';update app_private.qa_password_frames set state='armed',effect_table='public.profiles'::regclass,effect_op='UPDATE',effect_old=r,effect_new=r where backend_pid=pg_backend_pid() and sql_xid=pg_current_xact_id();perform app_private.qa_pw_consume('public.profiles'::regclass,'UPDATE',r,r);perform app_private.qa_pw_consume('public.profiles'::regclass,'UPDATE',r,r);end $$;`);
 await deny('one_atomic_consume_only',async()=>{await headers(actor,sid,h);await db.exec('select public.qa_fixture_double_consume()');});await db.exec('drop function public.qa_fixture_double_consume()');
 await db.exec(`create function public.qa_fixture_mismatched_row() returns void language plpgsql security definer set search_path='' as $$declare r jsonb;begin perform app_private.qa_pw_open('observe','${preparedReset}');select to_jsonb(x) into r from public.profiles x where id='${target}';update app_private.qa_password_frames set state='armed',effect_table='public.profiles'::regclass,effect_op='UPDATE',effect_old=r,effect_new=r where backend_pid=pg_backend_pid() and sql_xid=pg_current_xact_id();perform app_private.qa_pw_consume('public.profiles'::regclass,'UPDATE',r,r||jsonb_build_object('full_name','mismatch'));end $$;`);
 await deny('complete_NEW_row_not_partial_equality',async()=>{await headers(actor,sid,h);await db.exec('select public.qa_fixture_mismatched_row()');});await db.exec('drop function public.qa_fixture_mismatched_row()');
 await db.exec(`create function public.qa_fixture_unclosed_frame() returns void language plpgsql security definer set search_path='' as $$begin perform app_private.qa_pw_open('observe','${preparedReset}');end $$;`);
 await deny('COMMIT_cannot_persist_unclosed_private_frame',async()=>{await headers(actor,sid,h);await db.exec('select public.qa_fixture_unclosed_frame()');},'55000');await db.exec('drop function public.qa_fixture_unclosed_frame()');
 const immediateBefore=await snap();await db.exec('begin;set constraints app_private.qa_password_frame_completion immediate');await headers(actors.assistant,id(1003),id(99872));let immediateError;try{await scalar('select public.account_password_begin_internal($1,$2,$3,$4,$5)',[actors.assistant,id(1003),'fixture_assistant','change',id(99871)]);}catch(e){immediateError=e;}await db.exec('rollback');assert.equal(immediateError?.code,'55000');assert.deepEqual(await snap(),immediateBefore);check('premature_IMMEDIATE_callback_atomic_55000_before_cutoff');
 // Fresh wall clock after a genuine executor/profile wait; statement-start
 // eligibility cannot permit an original SID that expires during that wait.
 const waitUser=actors.otherAssistant,waitSid=id(1006),waitOp=id(99861),waitHandle=id(99862);
 await db.query("update auth.sessions set not_after=clock_timestamp()+interval '600 milliseconds' where id=$1",[waitSid]);const beforeWait=await snap();
 const {PGlite}=await import('file:///'+process.env.QA_LOCAL_PG_MODULE.replaceAll('\\\\','/'));const locker=new PGlite();await locker.verified;await locker.exec('begin');await locker.query('select id from public.profiles where id=$1 for update',[waitUser]);await headers(waitUser,waitSid,waitHandle);
 const pending=scalar('select public.account_password_begin_internal($1,$2,$3,$4,$5)',[waitUser,waitSid,'fixture_otherassistant','change',waitOp]);const captured=pending.then(()=>({allowed:true}),e=>({code:e.code}));await new Promise(r=>setTimeout(r,150));assert.equal((await locker.query('select wait_event_type from pg_stat_activity where pid=$1',[db.connection.pid])).rows[0].wait_event_type,'Lock');await new Promise(r=>setTimeout(r,700));await locker.exec('commit');await locker.close();assert.equal((await captured).code,'42501');assert.deepEqual(await snap(),beforeWait);check('fresh_wallclock_native_SID_expiry_after_actual_lock_wait');
 for(const t of ['qa_password_frames','qa_core_provision_context','qa_sql_operation_context'])assert.equal(await scalar('select count(*)::int from app_private.'+t),0);check('every_success_and_COMMIT_zero_private_state');
 report.status='PASS';
}catch(e){report.status='FAIL';report.failure={code:e.code||null,message:e.message,where:e.where||null};process.exitCode=1;}finally{await db.close();report.passed=report.checks.length;report.failed=report.status==='PASS'?0:1;report.skipped=0;report.xfail=0;fs.writeFileSync(path.join(O,'PASSWORD_INTEGRATION.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));}
