// Native loopback PostgreSQL only. Generated nonprotected synthetic office actor;
// provider proof below is fixture-only, never a real credential/provider call.
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import crypto from 'node:crypto';import {createPasswordGuardFixture} from './qa_password_fixture.mjs';
assert.ok(process.env.QA_LOCAL_PG_MODULE);assert.ok(process.env.QA_PW_REPORT_DIR);
const R={checks:[],provider_calls:0,remote_actions:0,protected_actor_used:false};
const f=await createPasswordGuardFixture({modulePath:process.env.QA_LOCAL_PG_MODULE,beforeGuards:async({db,actors})=>{assert.notEqual(actors.ceo,'0a1df502-9232-4ef5-af2d-df585ad7f187');await db.query("update public.user_roles set role_code='ceo_office_manager' where user_id=$1",[actors.ceo]);await db.query("update public.account_migration_users set role_code='ceo_office_manager' where migrated_user_id=$1",[actors.ceo]);}});
const {db,scalar,id,actors}=f;const actor=actors.ceo,sid=id(1004),op=id(63001),handle=id(63002),run=id(63004);R.engine=db.connection;
const hash=x=>crypto.createHash('sha256').update(JSON.stringify(x)).digest('hex');
const snap=async()=>{await db.exec('reset role');const o={};for(const t of (await db.query("select schemaname,tablename from pg_tables where schemaname in ('auth','public','app_private') order by 1,2")).rows)o[t.schemaname+'.'+t.tablename]=(await db.query(`select to_jsonb(t) row from "${t.schemaname}"."${t.tablename}" t order by to_jsonb(t)::text`)).rows;for(const s of (await db.query("select n.nspname,c.relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where c.relkind='S' and n.nspname in ('public','app_private','auth') order by 1,2")).rows)o['sequence:'+s.nspname+'.'+s.relname]=(await db.query(`select last_value::text,is_called from "${s.nspname}"."${s.relname}"`)).rows;return o;};
const headers=async(u=actor,s=sid,h=handle,extra={})=>{await db.exec('reset role');await db.query("select set_config('request.jwt.claims',$1,false),set_config('request.headers',$2,false)",[JSON.stringify({role:'service_role'}),JSON.stringify({'x-qa-actor-user':u,'x-qa-actor-sid':s,'x-qa-candidate-handle':h,...extra})]);await db.exec('set role service_role');};
const begin=async()=>{await headers();return scalar('select public.account_password_begin_internal($1,$2,$3,$4,$5)',[actor,sid,'fixture_ceo','reset',op]);};
const dispatch=async()=>{await headers();return (await db.query('select * from public.qa_password_dispatch_internal($1,1,$2)',[op,handle])).rows[0];};
const terminal=async(kind)=>{await headers();return kind==='finish'?scalar('select public.account_password_finish_internal($1,1)',[op]):kind==='fail'?scalar("select public.account_password_fail_internal($1,'provider_400')",[op]):scalar('select public.account_password_unknown_internal($1)',[op]);};
const mutate=async(sql,args)=>{await db.exec('reset role');const matched=/^(?:update|delete from|insert into) (public\.[a-z_]+)/.exec(sql)?.[1];const table=matched&&await scalar("select exists(select 1 from pg_trigger where tgrelid=$1::regclass and tgname='zz_combined_reference')",[matched])?matched:null;if(table)await db.exec(`alter table ${table} disable trigger zz_combined_reference`);try{await db.query(sql,args);}finally{if(table)await db.exec(`alter table ${table} enable trigger zz_combined_reference`);}}; // Trusted test-only drift; exact guard restored before every tested call.
const zero=async()=>{await db.exec('reset role');for(const t of ['qa_password_frames','qa_sql_operation_context','qa_core_provision_context'])assert.equal(await scalar('select count(*)::int from app_private.'+t),0);};
const unchanged=async(fn)=>{const b=await snap();await fn();assert.deepEqual(await snap(),b);};
const deny=async(fn,code='42501')=>{const b=await snap();await db.exec('savepoint negative');let e;try{await fn();}catch(x){e=x;}await db.exec('rollback to savepoint negative;release savepoint negative');assert.equal(e?.code,code,e?.message||'unexpectedly allowed');const a=await snap();assert.deepEqual(a,b);R.denials??=[];R.denials.push({code:e.code,message:e.message,before:hash(b),after:hash(a)});};
const scenario=async(name,fn)=>{await db.exec('reset role;begin');try{await fn();await zero();R.checks.push({name,pass:true});}catch(e){await db.exec('rollback');throw e;}await db.exec('rollback');};
const cohort=async()=>{await db.exec('reset role');await db.query("insert into app_private.qa_runs(run_id,phase,active,expires_at) values($1,'active',true,clock_timestamp()+interval '1 hour')",[run]);await db.query("insert into app_private.qa_account_manifest(user_id,canonical_key,login_alias,principal_class,run_id,owned_creation_operation,owned_creation_receipt_id) values($1,'fixture_ceo','fixture_ceo','current_owned_QA',$2,$3,$4)",[actor,run,id(63005),id(63006)]);await db.query("insert into app_private.qa_run_members values($1,$2,'ceo_office_manager',true)",[run,actor]);};
const finish=async()=>{await db.exec('reset role');await db.query("update auth.users set raw_app_meta_data=jsonb_build_object('msajed_password_operation',$2::text,'msajed_password_generation','1') where id=$1",[actor,op]);await db.query('insert into auth.sessions(id,user_id,created_at) values($1,$2,clock_timestamp())',[id(63003),actor]);const p={operation_id:op,generation:1,candidate_handle:handle,target_user_id:actor,target_email:'ceo@fixture.invalid',project_ref:'movzojtnkkmdsjhmlgtq',session_id:id(63003),issuer:'https://movzojtnkkmdsjhmlgtq.supabase.co/auth/v1',claim_role:'authenticated',observed_at:await scalar('select clock_timestamp()::text')};await headers(actor,sid,handle,{'x-qa-candidate-proof':JSON.stringify(p)});assert.equal((await scalar('select public.account_password_finish_internal($1,1)',[op])).status,'completed');};
const admitted=async()=>{assert.equal((await begin()).write_allowed,true);await zero();assert.equal(await scalar('select app_private.account_session_valid($1,$2,false)',[actor,sid]),false);const d=await dispatch();assert.equal(d.dispatch_state,'admitted_new');await unchanged(async()=>{const replay=await dispatch();assert.equal(replay.dispatch_state,'admitted_observed');assert.equal(replay.dispatch_token,d.dispatch_token);});};
try{
 await scenario('own_reset_begin_one_dispatch_finish_replay_exact_effects',async()=>{const before=await snap();await admitted();await finish();assert.equal(await scalar('select must_change_password from public.profiles where id=$1',[actor]),true);await unchanged(async()=>{assert.equal((await terminal('finish')).status,'completed');assert.equal((await begin()).write_allowed,false);await dispatch();assert.equal((await terminal('unknown')).status,'completed');assert.equal((await terminal('fail')).status,'completed');});const after=await snap();for(const [t,rows] of Object.entries(before)){if(t==='public.profiles')assert.deepEqual(after[t].filter(x=>x.row.id!==actor),rows.filter(x=>x.row.id!==actor));else if(t==='public.account_migration_users')assert.deepEqual(after[t].filter(x=>x.row.migrated_user_id!==actor),rows.filter(x=>x.row.migrated_user_id!==actor));else if(t==='app_private.account_credential_state')assert.deepEqual(after[t].filter(x=>x.row.user_id!==actor),rows.filter(x=>x.row.user_id!==actor));else if(t==='auth.users')assert.deepEqual(after[t].filter(x=>x.row.id!==actor),rows.filter(x=>x.row.id!==actor));else if(t==='auth.sessions')assert.deepEqual(after[t].filter(x=>x.row.id!==id(63003)),rows);else if(t==='app_private.account_password_operations')assert.deepEqual(after[t].filter(x=>x.row.operation_id!==op),rows);else if(t==='public.audit_log')assert.deepEqual(after[t].filter(x=>x.row.meta.operation_id!==op),rows);else if(t!=='sequence:public.audit_log_id_seq')assert.deepEqual(after[t],rows,t);}assert.equal(await scalar('select count(*)::int from public.audit_log where meta->>\'operation_id\'=$1',[op]),1);});
 await scenario('own_reset_fail_terminal_replay',async()=>{await admitted();assert.equal((await terminal('fail')).status,'failed');await unchanged(async()=>{assert.equal((await terminal('fail')).status,'failed');assert.equal((await begin()).write_allowed,false);await dispatch();assert.equal((await terminal('unknown')).status,'failed');});assert.equal(await scalar('select count(*)::int from public.audit_log where meta->>\'operation_id\'=$1',[op]),1);});
 await scenario('own_reset_unknown_reconciliation_finish',async()=>{await admitted();assert.equal((await terminal('unknown')).status,'uncertain');await unchanged(async()=>{assert.equal((await terminal('unknown')).status,'uncertain');assert.equal((await begin()).write_allowed,false);await dispatch();});await deny(()=>terminal('fail'),'P0001');await finish();});
 for(const [name,sql,args] of [
 ['unrelated_cutoff',"update app_private.account_credential_state set session_valid_after=session_valid_after+interval '1 microsecond' where user_id=$1",[actor]],
 ['permission',"insert into public.user_permissions values($1,'profiles.admin_reset_password','deny')",[actor]],
 ['office',"delete from public.user_roles where user_id=$1",[actor]],
 ['SID_created',"update auth.sessions set created_at=created_at+interval '1 microsecond' where id=$1",[sid]],
 ['SID_not_after',"update auth.sessions set not_after=clock_timestamp()+interval '1 hour' where id=$1",[sid]],
 ['identity_email',"update auth.users set email='changed@fixture.invalid' where id=$1",[actor]],
 ['profile_forced_reversal',"update public.profiles set must_change_password=false where id=$1",[actor]],
 ['registry_forced_reversal',"update public.account_migration_users set must_change_password=false where migrated_user_id=$1",[actor]],
 ['inactive',"update public.profiles set active=false where id=$1",[actor]]])await scenario(name+'_own_continuation_DENY',async()=>{await admitted();await db.exec('reset role');await mutate(sql,args);for(const fn of [dispatch,()=>terminal('unknown'),()=>terminal('finish'),()=>terminal('fail'),begin])await deny(fn);});
 await scenario('current_request_identity_candidate_DENY',async()=>{await admitted();for(const [u,s,h] of [[actors.manager,sid,handle],[actor,id(1002),handle],[actor,sid,id(63999)]])await deny(async()=>{await headers(u,s,h);await scalar('select public.account_password_unknown_internal($1)',[op]);});});
 await scenario('normal_business_new_reset_post_cutoff_DENY',async()=>{await admitted();await deny(async()=>{await headers();await db.query("insert into public.notifications(user_id,title,event_type) values($1,'deny','fixture')",[actor]);});await deny(async()=>{await headers();await scalar('select public.account_password_begin_internal($1,$2,$3,$4,$5)',[actor,sid,'fixture_ceo','reset',id(63998)]);});assert.equal(await scalar('select app_private.qa_session_live($1,$2,clock_timestamp(),true,$3)',[actor,sid,op]),false);});
 for(const state of ['halting','halted','expired']){
  await scenario(state+'_prepared_cannot_dispatch',async()=>{await cohort();await begin();await db.exec('reset role');await db.query("update app_private.qa_runs set phase=$2,active=false,expires_at=case when $2='expired' then clock_timestamp()-interval '1 second' else expires_at end where run_id=$1",[run,state]);await deny(dispatch);await deny(()=>terminal('unknown'));});
  for(const kind of ['finish','fail'])await scenario(state+'_admitted_'+kind+'_only',async()=>{await cohort();await admitted();await db.exec('reset role');await db.query("update app_private.qa_runs set phase=$2,active=false,expires_at=case when $2='expired' then clock_timestamp()-interval '1 second' else expires_at end where run_id=$1",[run,state]);await deny(async()=>{await headers();await db.query("insert into public.notifications(user_id,title,event_type) values($1,'deny','fixture')",[actor]);});if(kind==='finish'){assert.equal((await terminal('unknown')).status,'uncertain');await finish();}else assert.equal((await terminal('fail')).status,'failed');await unchanged(begin);});
 }
 await scenario('expired_original_SID_all_continuations_DENY',async()=>{await db.exec('reset role');await db.query("update auth.sessions set not_after=clock_timestamp()+interval '2 seconds' where id=$1",[sid]);await admitted();await new Promise(r=>setTimeout(r,2100));for(const fn of [dispatch,()=>terminal('unknown'),()=>terminal('finish'),()=>terminal('fail'),begin])await deny(fn);});
 for(const [name,sql,args] of [['forced',"update public.profiles set must_change_password=true where id=$1",[actor]],['initial_cutoff',"update app_private.account_credential_state set session_valid_after=clock_timestamp() where user_id=$1",[actor]],['initial_permission',"insert into public.user_permissions values($1,'profiles.admin_reset_password','deny')",[actor]]])await scenario(name+'_initial_not_admitted',async()=>{await mutate(sql,args);await deny(begin);});
 await db.exec('reset role');await db.query("update auth.sessions set not_after=clock_timestamp()+interval '2 seconds' where id=$1",[sid]);await db.exec('begin');assert.equal((await begin()).write_allowed,true);await db.exec('reset role;set constraints app_private.qa_password_frame_completion immediate;commit');await zero();R.checks.push({name:'native_COMMIT_and_forced_closure_zero_frames',pass:true});
 await dispatch();const beforeWait=await snap();const {PGlite}=await import('file:///'+process.env.QA_LOCAL_PG_MODULE.replaceAll('\\\\','/'));const locker=new PGlite();await locker.verified;assert.equal((await locker.query("select current_setting('data_directory') d")).rows[0].d.replaceAll('\\','/'),'C:/Users/FAiSAL/AppData/Local/hermes/cache/scratch/qa-local-postgres-ordering/data');await locker.exec('begin');await locker.query('select id from public.profiles where id=$1 for update',[actor]);await headers();const pending=scalar('select public.account_password_unknown_internal($1)',[op]);const captured=pending.then(()=>({allowed:true}),e=>({code:e.code,message:e.message}));try{await new Promise(r=>setTimeout(r,100));assert.equal((await locker.query('select wait_event_type from pg_stat_activity where pid=$1',[db.connection.pid])).rows[0].wait_event_type,'Lock');await new Promise(r=>setTimeout(r,2100));}finally{await locker.exec('commit');await locker.close();}assert.equal((await captured).code,'42501');assert.deepEqual(await snap(),beforeWait);await zero();R.checks.push({name:'own_reset_original_SID_fresh_expiry_after_actual_profile_lock_wait',pass:true});R.status='PASS';
}catch(e){R.status='FAIL';R.failure={code:e.code,message:e.message,where:e.where};process.exitCode=1;}finally{await db.exec('rollback');await db.close();R.passed=R.checks.length;R.failed=R.status==='PASS'?0:1;R.skipped=0;R.xfail=0;fs.writeFileSync(path.join(process.env.QA_PW_REPORT_DIR,process.argv.includes('--red')?'OWN_RESET_RED.json':'OWN_RESET_GREEN.json'),JSON.stringify(R,null,2));console.log(JSON.stringify(R,null,2));}
